CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "USERS" (
	"UserIDX"	INTEGER NOT NULL UNIQUE,
	"CallSign"	TEXT NOT NULL UNIQUE,
	"Name"	TEXT,
	"Active"	INTEGER DEFAULT 1,
	"DateJoined"	TEXT DEFAULT CURRENT_DATE,
	PRIMARY KEY("UserIDX" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "EXERCISES" (
	`ExerciseIDX`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Date`	TEXT NOT NULL,
	`Type`	TEXT NOT NULL,
	`Name`	TEXT NOT NULL,
	`Description`	TEXT NOT NULL
);
CREATE UNIQUE INDEX `Exercise_DateTypeName_Index` ON `EXERCISES` (
	`Date`	DESC,
	`Type`	ASC,
	`Name`	ASC
);
CREATE TABLE IF NOT EXISTS "EVENTS" (
	`EventIDX`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`UserIDX`	INTEGER NOT NULL,
	`ExerciseIDX`	INTEGER NOT NULL,
	`Latitude`	REAL NOT NULL,
	`Longitude`	REAL NOT NULL,
	`FeedbackCount`	INTEGER NOT NULL,
	`FeedbackText`	TEXT NOT NULL,
	`Context`	TEXT,
	CONSTRAINT `EventsExercises_FK` FOREIGN KEY(`ExerciseIDX`) REFERENCES `EXERCISES`(`ExerciseIDX`),
	CONSTRAINT `EventsUsers_FK` FOREIGN KEY(`UserIDX`) REFERENCES `USERS`(`UserIDX`)
);
CREATE UNIQUE INDEX `Event_UserExercise_Index` ON `EVENTS` (
	`UserIDX`	ASC,
	`ExerciseIDX`	ASC
);
